version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: adventureclub_postgres
    environment:
      POSTGRES_DB: AdventureClub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - adventureclub_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: adventureclub_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@adventureclub.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - adventureclub_network

volumes:
  postgres_data:

networks:
  adventureclub_network:
    driver: bridge